//This file is autogenerated from ../../boards/xilinx/atlys/rtl/verilog/include/orpsoc-defines.v do not change!
#ifndef _orpsoc_DEFINES_H_
#define _orpsoc_DEFINES_H_












































 #define XILINX
 #define XILINX_PLL
 #define FPGA_BOARD_XILINX_ATLYS
 #define IOCONFIG_XILINX_ATLYS
 #define BOARD_CLOCK_PERIOD 10000 

 #define JTAG_DEBUG

 #define XILINX_DDR2
 #define UART0

 #define GPIO0
 #define SPI0


 #define ETH0
 #define ETH0_PHY_RST











#define ARBITER_IBUS_WATCHDOG



#ifdef XILINX_DDR2
 #define ARBITER_IBUS_WATCHDOG_TIMER_WIDTH 20
#else
 #define ARBITER_IBUS_WATCHDOG_TIMER_WIDTH 6
#endif




#define ARBITER_DBUS_WATCHDOG

#ifdef XILINX_DDR2
 #define ARBITER_DBUS_WATCHDOG_TIMER_WIDTH 20
#else
 #define ARBITER_DBUS_WATCHDOG_TIMER_WIDTH 6
#endif





#define ARBITER_BYTEBUS_WATCHDOG_TIMER_WIDTH 9

#endif

